before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: aCCptqRU6eP1euG3TX2xAxRA00VPf5U6QohiqIo/crLt0mwxZgD3IPQNvXucvwfq6FU7LZ2WTsMXXfyVVCqK0eCIKvOyVojXl9t/XVuXga1K1VT4PNOLjEfzTiTT5Yar6yV5b/rWeJKpbDR+vW58ZMpWvBq/1x9kMUlzVLMv1xUdm2ZJ6FF9nzfYY4drHvD3+ozC8qKiIfb7cH5mE/8+vf7TywKwaEvuL0WDtcpQw+OZnBRevhtsxFP+Xf8mC2+3haIeaWGmNoajXejaIL1O/XrnoGmKnFQf5Jm95Nj9CWoW1bICjBlqJUSY4K6scTW01TO6kWnowJgtP0p2qxEFLCx8zJuVz6HGi7nIbrjhnvMAvOM9IL+PPq0MYt8KBbsqdb/QCnDR9Mm9Bf0o7z9ZnHy1H9bTvX3XzDkmq+kYJdRNi7UthKtcWvSAwlK9Mu3s1QkDh6+ZH7ulNeQJuL40UjvE9NUJdQ87iiCeMmMv5I6S/b2FrsP9/PKfot/Ef2U+RyRyGSabtdRwGcOiUUsjGQZvPtRSZEXkAVVzpH42A+1mqvNHf6BeQXpnklnNBocpsnzZvXJgzzmnMAKVd7gYPlzh8xbdO7NCyjhccW8lSTsa2zVq4BiLIm2oLrNrJ/liVFKGyy+sKe/Wlp/FvCLmOrgsibkLTuS7xJq+N+3wK9g= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml
    # - CRYPTO_AES_ENCRYPTED_SH: YjZiMmIwNjYyY2E0OGI5YjQ4ZmI3YTdkYmU4NjViN2I=I93wn43H8K4/eB5Wvi6A2irUFGh17rfCMer38OP/nGwK/4CqVaqXLLQlnG0aW/B+Zt+rUVfwxFxQplOTNqrK3WtMKw1307LZjVv/TPshn/uGxPUqpJTI075x+/b73WEYCXFvwCMwE1GVNiZTS8hGRmmhdLsFy7jlqQwGm0sp7VhUDRSmPsSH5rPplwKCvisqfcMBfCiGjfpXmrbX3gAnwDorfdHLKPFJlzUTcxPeEAjhT8pDckamS+V5scyCZwCqQdRFGOGva3KDyjBIOISbKkdhk1Yn8PczsJe7zrT+j2+mbBV32HPOQdmrwfPC/u3uLZSeTa+kob416KrOdHZWzk1p8DitQBgZUDwBd3ZVvxwc1lOrpciCunR3HXuaJIXKEkrzDu0V2uV/0V9vkeKFmFrTTnKad/4HPtB3GEfBkDPWEWOoYglEeIhMv5cBWdYnfFaV5Kkp145NI8IBQovJ07UyMk7uPcUEcY+V4s3RP3JZ2ZkfSOBXSMT5oa6m6DOX+w3ZNMsj4S0DYt/ncKvOOtqNOiXCChFGgwVd3hgfifgpiWF9CyqDL9AUkRgJyE9uFWccdPID8hw9hvHm1CinboH0CQZkX0/RbIy/R0S8nVS22HTX0SOgq6/yhacalRn6pkX1KxWgZc8gmgTlGvX/YcEzB31sQhy//jm69dd+XELcijk+jFmdf9jnW9Lyo366sRXXdnqFE5gDE4ZMOvyDyURDtKyBnaoy4FnMJY0HAfAIY46MN2/9ZKb9FQTigvVV # CRYPTO_AES_ENCRYPTED_SH
language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
